.PHONY: all
all:
	$(MAKE) build

#
# make
#

.ONESHELL:
SHELL = /bin/sh

MAKE = make -f $(shell find . -name Makefile.dos-container)
MAKEFLAGS += --no-print-directory

#
# tools
#

CMD_DOCKER ?= docker
DOS_CONT_DOCKERFILE = builder/Dockerfile.dos
DOS_CONT_NAME=dos:latest

build:
	${CMD_DOCKER} build \
		-f ${DOS_CONT_DOCKERFILE} \
		-t ${DOS_CONT_NAME} \
		tests/perftests/dos
